Intro to Numpy which is numerical python, used to allow several mathematical operations execute quickly.

In [31]:
import numpy as np
from time import process_time
import random

In [4]:
python_lst = [i for i in range(10000000)]
start_time = process_time()
python_lst = [i+5 for i in python_lst]
end_time = process_time()
print(end_time - start_time)

0.609375


In [5]:
np_array = np.array([i for i in range(10000000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.0


In [29]:
# 0d array/scalar
arr1 = np.array(42)

# 1d array called uni-dimensional
arr2 = np.array((1,2,3,4,5))

# 2d array used to represent matrices or 2nd order tensors.
arr3 = np.array([[1,2,3],[4,5,6]])

print(type(arr1))
print(arr1.dtype)
print(arr1)
print(arr1.shape)
print(arr2)
print(arr2.shape)
print(arr3)
print(arr3.shape)

print(arr3.ndim)

arr4 = np.array([1,2,3,4,5],ndmin=5)
print(arr4)

<class 'numpy.ndarray'>
int64
42
()
[1 2 3 4 5]
(5,)
[[1 2 3]
 [4 5 6]]
(2, 3)
2
[[[[[1 2 3 4 5]]]]]


In [14]:
arr = np.array([2.3,3.4,4,5],dtype=float)
print(arr)

[2.3 3.4 4.  5. ]


In [ ]:
ones = np.ones((3,4),dtype=int)
zeroes = np.zeros((2,3))
print(zeroes)
print("\n")
print(ones)
print("\n")
z = np.full((5,4),3)
print(z)

y = np.eye(4)
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
print(arr3[0][1])

2


In [34]:
# generating random numbers in numpy array

b = np.random.random((3,4)) # generates between 0 -> 1 random numbers
c = np.random.randint(10,100,(3,4))
print(c)

[[53 67 56 58]
 [62 48 77 36]
 [48 80 75 76]]


In [38]:
#Create an array of evenly spaced values.
d = np.linspace(10,30,5)
print(d)

# Create an array of evenly spaced values by specifying the step.
e = np.arange(10,30,7)
print(e)

[10. 15. 20. 25. 30.]
[10 17 24]


In [42]:
# convert list to an array

list2 = (10,20,20,20,50)
np_array = np.asarray(list2)
print(list2)
print(type(np_array))

(10, 20, 20, 20, 50)
<class 'numpy.ndarray'>


Array analysis

In [43]:
c = np.random.randint(10,90,(5,5))
print(c)

[[12 68 62 26 14]
 [38 70 33 79 10]
 [88 23 31 50 69]
 [16 54 87 86 20]
 [46 15 30 83 67]]


In [46]:
# array dimensions
print(c.shape)

# no. of dimensions
print(c.ndim)

# number of elements in an array
print(c.size)

# checking data type of elements
print(c.dtype)

(5, 5)
2
25
int32


Mathematical operations on a np array.

In [47]:
lst1 = [1,2,3,45]
lst2 = [6,7,8,9,10]
print(lst1+lst2)

[1, 2, 3, 45, 6, 7, 8, 9, 10]


In [51]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)


print(a+b)
print(a-b)
print(a*b)
print(a / b)

[[0 0 6]
 [9 0 9]
 [2 8 7]]
[[16 11 18]
 [11 19 14]
 [16 10 15]]
[[16 11 24]
 [20 19 23]
 [18 18 22]]
[[-16 -11 -12]
 [ -2 -19  -5]
 [-14  -2  -8]]
[[  0   0 108]
 [ 99   0 126]
 [ 32  80 105]]
[[0.         0.         0.33333333]
 [0.81818182 0.         0.64285714]
 [0.125      0.8        0.46666667]]


In [55]:
a = np.random.randint(0,10,(2,3))
transposed = np.transpose(a)
print(transposed)

[[9 5]
 [4 5]
 [1 1]]


In [56]:
b = np.random.randint(0,10,(2,3))
print(b)
print(b.shape)

[[2 1 1]
 [3 7 0]]
(2, 3)


In [57]:
c = b.reshape(3,2)
print(c)
print(c.shape)

[[2 1]
 [1 3]
 [7 0]]
(3, 2)
